#!/bin/bash

# postinst: This script runs after the package is installed\
# Ensure the installation directory is set up
if [ ! -d "/usr/local/lib/pinstaller" ]; then
  mkdir -p /usr/local/lib/pinstaller
fi

exit 0
